In [1]:
import tensorflow as tf


In [2]:
print(tf.__version__)

2.17.0


# Initialization


In [3]:
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
x=tf.constant(4,shape=(1,1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [10]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
x=tf.ones(3)
print(x)

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [12]:
x=tf.zeros(3)
print(x)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [14]:
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 0.45517743 -0.23784742 -0.36029595]
 [ 1.6542573  -0.7497078  -1.1875812 ]
 [ 0.33661327  0.47534844  1.4068861 ]], shape=(3, 3), dtype=float32)


In [18]:
x=tf.random.uniform((3,3),minval=0,maxval=1)
print(x)

tf.Tensor(
[[0.78964424 0.31478846 0.33267605]
 [0.05616748 0.02254677 0.65799034]
 [0.34818292 0.7988082  0.78118694]], shape=(3, 3), dtype=float32)


In [19]:
x=tf.range(3)
print(x)

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [22]:
x=tf.range(start=0,limit=10,delta=2)
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [23]:
x=tf.cast(x,dtype=tf.float64)#Commonly used for Deep Learning float64
print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float64)


In [24]:
x=tf.constant([1,2,3])
print(x)
y=tf.constant([9,8,7])
print(y)
print(x+y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([9 8 7], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)
